version: '3'

services:
  database:
    image: postgres:11.4-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
    expose:
      - 5432

  application:
    build:
      context: ./
      dockerfile: docker/application/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:8080
    command: java -jar ktor-amp-application.jar -server
                -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -XX:InitialRAMFraction=2
                -XX:MinRAMFraction=2
                -XX:MaxRAMFraction=2
                -XX:+UseG1GC
                -XX:MaxGCPauseMillis=100
                -XX:+UseStringDeduplication
    volumes:
      - ./:/var/www
      - application-jar:/var/www/
    depends_on:
      - database
      - gradle

  gradle:
    build:
      context: ./
      dockerfile: docker/gradle/Dockerfile
    environment:
      TZ: Asia/Tokyo
    command: ./gradlew -t build
    volumes:
      - ./:/var/www/
      - application-jar:/var/www/build/libs/

volumes:
  database:
  application-jar: